#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置

---
server:
  port: 8001

mybatis-plus:
  config-location:
  type-aliases-package: com.miranda.srpingcloud.entities
  mapper-locations:  classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  profiles: dev # 开发环境
  application:
  name: microservice-product-config # ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8 #数 据库连接地址，*****注意库名 db01***************
  username: root
  password: root
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 150
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
  defaultZone:
    http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    preferIpAddress: true

---

server:
  port: 8001

mybatis-plus:
  config-location:
  type-aliases-package: com.miranda.srpingcloud.entities
  mapper-locations:  classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true # 服务注册，true表示将自已注册到Eureka服务中
    fetch-registry: true # 服务发现，true表示自己会从Eureka服务中获取注册信息
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}-hystrix
    preferIpAddress: true
